CREATE TABLE [dbo].[Associer] (
    [JeuId] UNIQUEIDENTIFIER NOT NULL,
    [TagId] UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY CLUSTERED ([JeuId] ASC, [TagId] ASC),
    FOREIGN KEY ([JeuId]) REFERENCES [dbo].[Jeux] ([JeuId]) ON DELETE CASCADE,
    FOREIGN KEY ([TagId]) REFERENCES [dbo].[Tag] ([TagId]) ON DELETE CASCADE
);

