CREATE TABLE [dbo].[Tag] (
    [TagId]  UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [NomTag] NVARCHAR (50)    NOT NULL,
    PRIMARY KEY CLUSTERED ([TagId] ASC),
    UNIQUE NONCLUSTERED ([NomTag] ASC)
);

